webpack_encore:
    builds:
        ezplatform: "%kernel.project_dir%/public/assets/ezplatform/build"

framework:
    assets:
        json_manifest_path: ~
        packages:
            ezplatform:
                json_manifest_path: '%kernel.project_dir%/public/assets/ezplatform/build/manifest.json'

