webpack_encore:
    builds:
        ezplatform: "%kernel.project_dir%/public/assets/ezplatform/build"
        ibexa: "%kernel.project_dir%/public/assets/ibexa/build"
        richtext: "%kernel.project_dir%/public/assets/richtext/build"

framework:
    assets:
        json_manifest_path: ~
        packages:
            ezplatform:
                json_manifest_path: '%kernel.project_dir%/public/assets/ezplatform/build/manifest.json'
            ibexa:
                json_manifest_path: '%kernel.project_dir%/public/assets/ibexa/build/manifest.json'
