ibexa.rest:
    resource: '@IbexaRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

ibexa.rest.options:
    resource: '@IbexaRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options
