ezplatform_rest:
    resource: '@IbexaRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'

ezplatform_rest_options:
    resource: '@IbexaRestBundle/Resources/config/routing.yml'
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options
