<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Symfony\WebpackEncoreBundle\WebpackEncoreBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Bazinga\Bundle\JsTranslationBundle\BazingaJsTranslationBundle::class => ['all' => true],
    FOS\JsRoutingBundle\FOSJsRoutingBundle::class => ['all' => true],
    FOS\HttpCacheBundle\FOSHttpCacheBundle::class => ['all' => true],
    JMS\TranslationBundle\JMSTranslationBundle::class => ['all' => true],
    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
    Nelmio\CorsBundle\NelmioCorsBundle::class => ['all' => true],
    Oneup\FlysystemBundle\OneupFlysystemBundle::class => ['all' => true],
    Knp\Bundle\MenuBundle\KnpMenuBundle::class => ['all' => true],
    Ibexa\Bundle\Core\IbexaCoreBundle::class => ['all' => true],
    Ibexa\Bundle\CorePersistence\IbexaCorePersistenceBundle::class => ['all' => true],
    Ibexa\Bundle\CoreSearch\IbexaCoreSearchBundle::class => ['all' => true],
    Ibexa\Bundle\LegacySearchEngine\IbexaLegacySearchEngineBundle::class => ['all' => true],
    Ibexa\Bundle\IO\IbexaIOBundle::class => ['all' => true],
    Ibexa\Bundle\Debug\IbexaDebugBundle::class => ['dev' => true, 'test' => true, 'behat' => true],
    Ibexa\Bundle\HttpCache\IbexaHttpCacheBundle::class => ['all' => true],
    Ibexa\Bundle\Rest\IbexaRestBundle::class => ['all' => true],
    Ibexa\Bundle\Solr\IbexaSolrBundle::class => ['all' => true],
    Ibexa\Bundle\SystemInfo\IbexaSystemInfoBundle::class => ['all' => true],
    Ibexa\Bundle\Cron\IbexaCronBundle::class => ['all' => true],
    Ibexa\Bundle\RepositoryInstaller\IbexaRepositoryInstallerBundle::class => ['all' => true],
    Ibexa\Bundle\DoctrineSchema\DoctrineSchemaBundle::class => ['all' => true],
    Ibexa\Bundle\ContentForms\IbexaContentFormsBundle::class => ['all' => true],
    Ibexa\Bundle\DesignEngine\IbexaDesignEngineBundle::class => ['all' => true],
    Ibexa\Bundle\StandardDesign\IbexaStandardDesignBundle::class => ['all' => true],
    Ibexa\Bundle\FieldTypeRichText\IbexaFieldTypeRichTextBundle::class => ['all' => true],
    Ibexa\Bundle\AdminUi\IbexaAdminUiBundle::class => ['all' => true],
    Ibexa\Bundle\User\IbexaUserBundle::class => ['all' => true],
    Ibexa\Bundle\AdminUiAssets\IbexaAdminUiAssetsBundle::class => ['all' => true],
    Ibexa\Bundle\FieldTypeMatrix\IbexaFieldTypeMatrixBundle::class => ['all' => true],
    Ibexa\Bundle\GraphQL\IbexaGraphQLBundle::class => ['all' => true],
    Ibexa\Bundle\FieldTypeQuery\IbexaFieldTypeQueryBundle::class => ['all' => true],
    Ibexa\Bundle\Search\IbexaSearchBundle::class => ['all' => true],
    Ibexa\Bundle\Notifications\IbexaNotificationsBundle::class => ['all' => true],
    Overblog\GraphQLBundle\OverblogGraphQLBundle::class => ['all' => true],
    Overblog\GraphiQLBundle\OverblogGraphiQLBundle::class => ['dev' => true],
    Twig\Extra\TwigExtraBundle\TwigExtraBundle::class => ['all' => true],
    BabDev\PagerfantaBundle\BabDevPagerfantaBundle::class => ['all' => true],
    Hautelook\TemplatedUriBundle\HautelookTemplatedUriBundle::class => ['all' => true],
    Lexik\Bundle\JWTAuthenticationBundle\LexikJWTAuthenticationBundle::class => ['all' => true],
];
