name: Browser tests

on:
    push:
        tags:
            - 'v4*'

jobs:
    regression-oss-setup1:
        name: "PHP 7.4/Node 14/PostgreSQL/Varnish/Redis"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: ${{ github.ref_name }}
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            php-image: "ezsystems/php:7.4-v2-node14"
            job-count: 2
            timeout: 60
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-oss-setup2:
        name: "PHP 8.1/Node 16/MySQL/Compatibility layer"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "oss"
            project-version: ${{ github.ref_name }}
            test-suite: "--profile=regression --suite=oss"
            test-setup-phase-1: "--profile=regression --suite=setup-oss --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            multirepository: true
            use-compatibility-layer: true
            job-count: 2
            timeout: 60
            php-image: "ezsystems/php:8.1-v2-node16"
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
