name: Browser tests

on:
    push:
        tags:
            - 'v*'

jobs:
    trigger-browser-tests:
        name: Browser tests
        runs-on: ubuntu-26.04
        steps:
          - uses: actions/create-github-app-token@v3
            name: Generate token
            id: generate_token
            with:
                client-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                owner: ${{ github.repository_owner }}
          - name: Trigger browser tests
            shell: bash
            run: |
                gh api --method POST "/repos/ibexa/oss/actions/workflows/browser-tests.yml/dispatches" \
                  -f ref="${{ github.ref_name }}" \
                  -f "inputs[send-success-notification]=true" \
                  -f "inputs[project-version]=${{ github.ref_name }}"
            env:
                GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
